title = "Akua's Blog"
motto = "Welcome to my blog!"
extra_js = "script.js"
abouts = [
    "学生@<a href=\"https://www.ahu.edu.cn/\">安徽大学</a>、逆向CTFer@iSEAL; <a href=\"https://r3kapig.com/\">r3kapig</a>、二进制安全爱好者",
    "gaoyucandev@gmail.com | <a href=\"https://github.com/GaoYuCan\">github</a>",
]

[[posts]]
time = "2021-01-01"
name = "Post 1"
url = "/posts/aa"

[[posts]]
time = "2021-02-01"
name = "Post 2"
url = "/posts/bb"

[[projects]]
name = "Project 1"
url = "https://example.com/project1"

[[projects]]
name = "Project 2"
url = "https://example.com/project2"

[[friends]]
name = "Friend 1"
url = "https://example.com/friend1"

[[friends]]
name = "Friend 2"
url = "https://example.com/friend2"
